### ISSUE TITLE
getting "Kommando nicht gefunden" to command "mvn install"

### ISSUE THREAD

**Issue by mschlen** [peterdikant/SimpleDmxEngine#1]
Hello,

thanks for your work and documentation on this project. I prepared my rasp with OLA and I can control my DMX-device with the onboard tool. The problem is now, that i can not compile the SimpleDmxEngine in the project folder. I always get the message "bash: mvn: Kommando nicht gefunden". Is there something further I have to know?

Thanks in advance

**Comment by peterdikant** [comment]
It seems like you need to install maven: https://maven.apache.org

**Comment by mschlen** [comment]
thanks for your fast reply, I will try that.
Yes, that was the problem. Thank you very much!
